#!/usr/bin/env bash
set -euo pipefail

# images/publish.sh — Upload a built image to Backblaze B2 (and optionally update manifest)
#
# Usage:
#   ./images/publish.sh [--upload-only] <image-name> <version> <image-file>
#   ./images/publish.sh --upload-only base 1.0.0 images/artifacts/mps-base-amd64.qcow2.img
#   ./images/publish.sh base 1.0.0 images/artifacts/mps-base-amd64.qcow2.img
#
# Modes:
#   --upload-only   Upload image + .sha256 sidecar to B2, skip manifest update.
#                   Used by CI runners; manifest is updated separately by update-manifest.sh.
#   (default)       Upload image + sidecar, then update manifest. For local dev.
#
# Requires: b2 CLI v4, jq, yq (optional, for x-mps metadata in default mode)
#
# Environment:
#   B2_APPLICATION_KEY_ID — B2 application key ID (required, read by b2 CLI)
#   B2_APPLICATION_KEY    — B2 application key (required, read by b2 CLI)
#   MPS_B2_BUCKET         — B2 bucket name (default: from config/defaults.env)

# shellcheck source=lib/publish-common.sh
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib/publish-common.sh"
publish_init

# Parse flags
UPLOAD_ONLY=false
if [[ "${1:-}" == "--upload-only" ]]; then
    UPLOAD_ONLY=true
    shift
fi

IMAGE_NAME="${1:?Usage: publish.sh [--upload-only] <image-name> <version> <image-file>}"
VERSION="${2:?Usage: publish.sh [--upload-only] <image-name> <version> <image-file>}"
IMAGE_FILE="${3:?Usage: publish.sh [--upload-only] <image-name> <version> <image-file>}"

_validate_semver "$VERSION"

if [[ ! -f "$IMAGE_FILE" ]]; then
    echo "ERROR: Image file not found: $IMAGE_FILE"
    exit 1
fi

# Detect architecture (prefer TARGET_ARCH env var for cross-built images)
if [[ -n "${TARGET_ARCH:-}" ]]; then
    ARCH="$TARGET_ARCH"
else
    ARCH="$(dpkg --print-architecture 2>/dev/null || uname -m)"
    case "$ARCH" in
        x86_64) ARCH="amd64" ;;
        aarch64) ARCH="arm64" ;;
    esac
fi

if [[ "$UPLOAD_ONLY" == "true" ]]; then
    echo "=== Uploading ${IMAGE_NAME}:${VERSION} (${ARCH}) ==="
else
    echo "=== Publishing ${IMAGE_NAME}:${VERSION} (${ARCH}) ==="
fi

# Read SHA256 from .sha256 sidecar (generated by Packer build)
SHA256_FILE="${IMAGE_FILE}.sha256"
if [[ ! -f "$SHA256_FILE" ]]; then
    echo "ERROR: SHA256 sidecar not found: ${SHA256_FILE}"
    echo "Expected alongside image file (generated by 'make image-*')"
    exit 1
fi
SHA256="$(awk '{print $1}' "$SHA256_FILE")"
echo "SHA256: ${SHA256} (from ${SHA256_FILE})"

# ---------- Upload image to B2 ----------
B2_PATH="${IMAGE_NAME}/${VERSION}/${ARCH}.img"
echo "Uploading image to b2://${BUCKET}/${B2_PATH}..."
b2 file upload "${BUCKET}" "$IMAGE_FILE" "$B2_PATH"
echo "Image upload complete."

# Upload .sha256 sidecar (used by update-manifest.sh in fan-in CI flow)
B2_SHA_PATH="${B2_PATH}.sha256"
echo "Uploading sidecar to b2://${BUCKET}/${B2_SHA_PATH}..."
b2 file upload "${BUCKET}" "$SHA256_FILE" "$B2_SHA_PATH"
echo "Sidecar upload complete."

# Clean up old versions of both files
echo "Cleaning up old file versions..."
_b2_cleanup_old_versions "$B2_PATH"
_b2_cleanup_old_versions "$B2_SHA_PATH"

# ---------- Cancel unfinished large file uploads ----------
# Failed/interrupted uploads leave partial data that consumes storage.
# Safe to cancel all — no legitimate in-progress uploads after a completed upload.
echo "Checking for unfinished large file uploads..."
CANCEL_OUTPUT="$(b2 file large unfinished cancel "b2://${BUCKET}" 2>&1)" || true
if [[ -n "$CANCEL_OUTPUT" ]]; then
    echo "$CANCEL_OUTPUT"
else
    echo "No unfinished uploads found."
fi

# ---------- Upload-only mode: stop here ----------
if [[ "$UPLOAD_ONLY" == "true" ]]; then
    echo ""
    echo "=== Upload complete (manifest not updated) ==="
    echo "  Image:    ${IMAGE_NAME}:${VERSION} (${ARCH})"
    echo "  B2 path:  b2://${BUCKET}/${B2_PATH}"
    echo "  Sidecar:  b2://${BUCKET}/${B2_SHA_PATH}"
    echo "  SHA256:   ${SHA256}"
    echo ""
    echo "Run update-manifest.sh to update the manifest after all uploads finish."
    exit 0
fi

# ---------- Update manifest (default mode, for local dev) ----------
BUILD_DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

# Get file size for manifest
FILE_SIZE="$(stat -c '%s' "$IMAGE_FILE")"

# Download the remote manifest from B2 (source of truth for multi-arch publishing).
# Falls back to the local skeleton manifest for the very first publish.
echo "Fetching remote manifest..."
REMOTE_MANIFEST="$(mktemp)"
if b2 file download "b2://${BUCKET}/manifest.json" "$REMOTE_MANIFEST" 2>/dev/null; then
    echo "Using remote manifest from B2."
else
    echo "Remote manifest not found, using local skeleton."
    if [[ ! -f "$MANIFEST_FILE" ]]; then
        echo "ERROR: Local manifest not found at ${MANIFEST_FILE}"
        rm -f "$REMOTE_MANIFEST"
        exit 1
    fi
    cp "$MANIFEST_FILE" "$REMOTE_MANIFEST"
fi

# Extract x-mps metadata from the layer YAML for this flavor
LAYER_FILE="${SCRIPT_DIR}/layers/${IMAGE_NAME}.yaml"
_read_xmps_metadata "$LAYER_FILE"

# Merge new entry into manifest
echo "Updating manifest..."
RELATIVE_URL="${IMAGE_NAME}/${VERSION}/${ARCH}.img"
TMP_MANIFEST="$(mktemp)"

_b2_merge_manifest_entry "$REMOTE_MANIFEST" "$TMP_MANIFEST" \
    "$IMAGE_NAME" "$VERSION" "$ARCH" "$RELATIVE_URL" "$SHA256" "$BUILD_DATE" \
    "$FILE_SIZE" "$META_DISK_SIZE" "$META_MIN_PROFILE" "$META_MIN_DISK" \
    "$META_MIN_MEMORY" "$META_MIN_CPUS"

# Upload updated manifest to B2 (old versions intentionally kept for audit/reconciliation)
echo "Uploading manifest to b2://${BUCKET}/manifest.json..."
b2 file upload "${BUCKET}" "$TMP_MANIFEST" "manifest.json"

# Generate index pages
echo "Generating index pages..."
bash "${SCRIPT_DIR}/generate-index.sh" "$TMP_MANIFEST" "$BUCKET"

rm -f "$REMOTE_MANIFEST" "$TMP_MANIFEST"
echo "Manifest updated: ${IMAGE_NAME}:${VERSION} (${ARCH})"

echo ""
echo "=== Published successfully ==="
echo "  Image:      ${IMAGE_NAME}:${VERSION} (${ARCH})"
echo "  B2 path:    b2://${BUCKET}/${B2_PATH}"
echo "  SHA256:     ${SHA256}"
echo "  Build date: ${BUILD_DATE}"
echo "  Manifest:   b2://${BUCKET}/manifest.json"
