#!/usr/bin/env bash
set -euo pipefail

# images/publish.sh — Upload a built image to Backblaze B2 (and optionally update manifest)
#
# Usage:
#   ./images/publish.sh [--upload-only] <image-name> <version> <image-file>
#   ./images/publish.sh --upload-only base 1.0.0 images/artifacts/mps-base-amd64.qcow2.img
#   ./images/publish.sh base 1.0.0 images/artifacts/mps-base-amd64.qcow2.img
#
# Modes:
#   --upload-only   Upload image + .sha256 sidecar to B2, skip manifest update.
#                   Used by CI runners; manifest is updated separately by update-manifest.sh.
#   (default)       Upload image + sidecar, then update manifest. For local dev.
#
# Requires: b2 CLI v4, jq, yq (optional, for x-mps metadata in default mode)
#
# Environment:
#   B2_APPLICATION_KEY_ID — B2 application key ID (required, read by b2 CLI)
#   B2_APPLICATION_KEY    — B2 application key (required, read by b2 CLI)
#   MPS_B2_BUCKET         — B2 bucket name (default: from config/defaults.env)
#   MPS_B2_BUCKET_PREFIX  — Path prefix in bucket (default: mps)

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MPS_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Load defaults
# shellcheck source=../config/defaults.env
source "${MPS_ROOT}/config/defaults.env"

# Parse flags
UPLOAD_ONLY=false
if [[ "${1:-}" == "--upload-only" ]]; then
    UPLOAD_ONLY=true
    shift
fi

IMAGE_NAME="${1:?Usage: publish.sh [--upload-only] <image-name> <version> <image-file>}"
VERSION="${2:?Usage: publish.sh [--upload-only] <image-name> <version> <image-file>}"
IMAGE_FILE="${3:?Usage: publish.sh [--upload-only] <image-name> <version> <image-file>}"

BUCKET="${MPS_B2_BUCKET:-mps-images}"
PREFIX="${MPS_B2_BUCKET_PREFIX:-mps}"
MANIFEST_FILE="${SCRIPT_DIR}/manifest.json"

# Validate SemVer format
if [[ ! "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    echo "ERROR: Version must be SemVer format (e.g., 1.0.0). Got: $VERSION"
    exit 1
fi

if [[ ! -f "$IMAGE_FILE" ]]; then
    echo "ERROR: Image file not found: $IMAGE_FILE"
    exit 1
fi

# Detect architecture (prefer TARGET_ARCH env var for cross-built images)
if [[ -n "${TARGET_ARCH:-}" ]]; then
    ARCH="$TARGET_ARCH"
else
    ARCH="$(dpkg --print-architecture 2>/dev/null || uname -m)"
    case "$ARCH" in
        x86_64) ARCH="amd64" ;;
        aarch64) ARCH="arm64" ;;
    esac
fi

if [[ "$UPLOAD_ONLY" == "true" ]]; then
    echo "=== Uploading ${IMAGE_NAME}:${VERSION} (${ARCH}) ==="
else
    echo "=== Publishing ${IMAGE_NAME}:${VERSION} (${ARCH}) ==="
fi

# Read SHA256 from .sha256 sidecar (generated by Packer build)
SHA256_FILE="${IMAGE_FILE}.sha256"
if [[ ! -f "$SHA256_FILE" ]]; then
    echo "ERROR: SHA256 sidecar not found: ${SHA256_FILE}"
    echo "Expected alongside image file (generated by 'make image-*')"
    exit 1
fi
SHA256="$(awk '{print $1}' "$SHA256_FILE")"
echo "SHA256: ${SHA256} (from ${SHA256_FILE})"

# ---------- Helper: delete old file versions ----------
# B2 retains all file versions; old versions still consume storage.
# Deletes all but the latest (newest) version of a specific file.
_b2_cleanup_old_versions() {
    local file_path="$1"

    # List all versions in the parent directory (b2 ls --versions: newest first)
    local parent_dir
    parent_dir="$(dirname "$file_path")"

    local versions
    versions="$(b2 ls --json --versions "b2://${BUCKET}/${parent_dir}/" 2>/dev/null)" || return 0

    # Filter to upload actions matching the exact file path, skip newest, collect old IDs
    local old_ids
    old_ids="$(echo "$versions" \
        | jq -r --arg fp "$file_path" \
            'select(.action == "upload" and .fileName == $fp) | .fileId' \
        | tail -n +2)"

    [[ -n "$old_ids" ]] || return 0

    local count=0
    while IFS= read -r file_id; do
        [[ -n "$file_id" ]] || continue
        echo "  Deleting old version: ${file_id}"
        b2 file delete "b2id://${file_id}" || true
        count=$((count + 1))
    done <<< "$old_ids"
    echo "  Removed ${count} old version(s)."
}

# ---------- Upload image to B2 ----------
B2_PATH="${PREFIX}/${IMAGE_NAME}/${VERSION}/${ARCH}.img"
echo "Uploading image to b2://${BUCKET}/${B2_PATH}..."
b2 file upload --no-progress "${BUCKET}" "$IMAGE_FILE" "$B2_PATH"
echo "Image upload complete."

# Upload .sha256 sidecar (used by update-manifest.sh in fan-in CI flow)
B2_SHA_PATH="${B2_PATH}.sha256"
echo "Uploading sidecar to b2://${BUCKET}/${B2_SHA_PATH}..."
b2 file upload --no-progress "${BUCKET}" "$SHA256_FILE" "$B2_SHA_PATH"
echo "Sidecar upload complete."

# Clean up old versions of both files
echo "Cleaning up old file versions..."
_b2_cleanup_old_versions "$B2_PATH"
_b2_cleanup_old_versions "$B2_SHA_PATH"

# ---------- Cancel unfinished large file uploads ----------
# Failed/interrupted uploads leave partial data that consumes storage.
# Safe to cancel all — no legitimate in-progress uploads after a completed upload.
echo "Canceling any unfinished large file uploads..."
b2 file large unfinished cancel "b2://${BUCKET}" 2>/dev/null || true

# ---------- Upload-only mode: stop here ----------
if [[ "$UPLOAD_ONLY" == "true" ]]; then
    echo ""
    echo "=== Upload complete (manifest not updated) ==="
    echo "  Image:    ${IMAGE_NAME}:${VERSION} (${ARCH})"
    echo "  B2 path:  b2://${BUCKET}/${B2_PATH}"
    echo "  Sidecar:  b2://${BUCKET}/${B2_SHA_PATH}"
    echo "  SHA256:   ${SHA256}"
    echo ""
    echo "Run update-manifest.sh to update the manifest after all uploads finish."
    exit 0
fi

# ---------- Update manifest (default mode, for local dev) ----------
BUILD_DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

# Download the remote manifest from B2 (source of truth for multi-arch publishing).
# Falls back to the local skeleton manifest for the very first publish.
echo "Fetching remote manifest..."
REMOTE_MANIFEST="$(mktemp)"
if b2 file download "b2://${BUCKET}/${PREFIX}/manifest.json" "$REMOTE_MANIFEST" 2>/dev/null; then
    echo "Using remote manifest from B2."
else
    echo "Remote manifest not found, using local skeleton."
    if [[ ! -f "$MANIFEST_FILE" ]]; then
        echo "ERROR: Local manifest not found at ${MANIFEST_FILE}"
        rm -f "$REMOTE_MANIFEST"
        exit 1
    fi
    cp "$MANIFEST_FILE" "$REMOTE_MANIFEST"
fi

# Extract x-mps metadata from the layer YAML for this flavor
LAYER_FILE="${SCRIPT_DIR}/layers/${IMAGE_NAME}.yaml"

META_DISK_SIZE=""
META_MIN_PROFILE=""
META_MIN_DISK=""
META_MIN_MEMORY=""
META_MIN_CPUS=""
if [[ -f "$LAYER_FILE" ]] && command -v yq &>/dev/null; then
    META_DISK_SIZE="$(yq '.x-mps.disk_size // ""' "$LAYER_FILE")"
    META_MIN_PROFILE="$(yq '.x-mps.min_profile // ""' "$LAYER_FILE")"
    META_MIN_DISK="$(yq '.x-mps.min_disk // ""' "$LAYER_FILE")"
    META_MIN_MEMORY="$(yq '.x-mps.min_memory // ""' "$LAYER_FILE")"
    META_MIN_CPUS="$(yq '.x-mps.min_cpus // ""' "$LAYER_FILE")"
fi

# Merge new entry into manifest: version data, arch-specific data, x-mps metadata
echo "Updating manifest..."
RELATIVE_URL="${IMAGE_NAME}/${VERSION}/${ARCH}.img"
TMP_MANIFEST="$(mktemp)"

jq \
    --arg name "$IMAGE_NAME" \
    --arg ver "$VERSION" \
    --arg arch "$ARCH" \
    --arg url "$RELATIVE_URL" \
    --arg sha "$SHA256" \
    --arg build_date "$BUILD_DATE" \
    --arg disk_size "$META_DISK_SIZE" \
    --arg min_profile "$META_MIN_PROFILE" \
    --arg min_disk "$META_MIN_DISK" \
    --arg min_memory "$META_MIN_MEMORY" \
    --arg min_cpus "$META_MIN_CPUS" \
    '
    # Ensure image entry exists
    .images[$name] //= {"description": "", "versions": {}, "latest": null} |
    # Inject x-mps metadata (overwrite if present)
    (if $disk_size != "" then .images[$name].disk_size = $disk_size else . end) |
    (if $min_profile != "" then .images[$name].min_profile = $min_profile else . end) |
    (if $min_disk != "" then .images[$name].min_disk = $min_disk else . end) |
    (if $min_memory != "" then .images[$name].min_memory = $min_memory else . end) |
    (if $min_cpus != "" then .images[$name].min_cpus = ($min_cpus | tonumber) else . end) |
    # Ensure version entry exists
    .images[$name].versions[$ver] //= {} |
    # Set arch-specific data
    .images[$name].versions[$ver][$arch] = {
        "url": $url,
        "sha256": $sha,
        "build_date": $build_date
    } |
    # Update latest pointer
    .images[$name].latest = $ver
    ' "$REMOTE_MANIFEST" > "$TMP_MANIFEST"

# Upload updated manifest to B2 (old versions intentionally kept for audit/reconciliation)
echo "Uploading manifest to b2://${BUCKET}/${PREFIX}/manifest.json..."
b2 file upload --no-progress "${BUCKET}" "$TMP_MANIFEST" "${PREFIX}/manifest.json"

rm -f "$REMOTE_MANIFEST" "$TMP_MANIFEST"
echo "Manifest updated: ${IMAGE_NAME}:${VERSION} (${ARCH})"

echo ""
echo "=== Published successfully ==="
echo "  Image:      ${IMAGE_NAME}:${VERSION} (${ARCH})"
echo "  B2 path:    b2://${BUCKET}/${B2_PATH}"
echo "  SHA256:     ${SHA256}"
echo "  Build date: ${BUILD_DATE}"
echo "  Manifest:   b2://${BUCKET}/${PREFIX}/manifest.json"
